### ISSUE TITLE
Luyện tập tạo model

### ISSUE THREAD

**Issue by ngochan21098** [ngochan21098/learning-django-basic#1]
## Đề bài 
Tạo 3 model tuỳ ý trong đó có ít nhất 5 kiểu dữ liệu khác nhau và 1 model có 2 Foreignkey đến 2 model còn lại.

**Comment by ngochan21098** [comment]
@dangdinhhienpy please review my pull request. Thanks.

**Comment by ngochan21098** [comment]
@dangdinhhienpy 
Sorry, I forgot to push new code to 'main' instead of creating new branch. 
The newest code is here
https://github.com/ngochan21098/learning-django-basic/blob/main/han_first_project/users/models.py

The above PR is when I tried to push code as a PR, just ignore it

**Comment by ddhienpy** [comment]
@ngochan21098 
Your PR looks so good 👍 

> Sorry, I forgot to push new code to 'main' instead of creating new branch.

You can revert this commit by some steps below:
`git logs` (Show all commits at the current branch, then you copy the last commit_id)
`git revert commit_id commit_id commit_id` (You can add one/multiple commits)
`git push origin branch_name` (exp: git push origin main)

Ref: https://stackoverflow.com/questions/22682870/how-can-i-undo-pushed-commits-using-git
