### ISSUE TITLE
[Exercise about Models] Create, Update, Delete model

### ISSUE THREAD

**Issue by ddhienpy** [ngochan21098/learning-django-basic#3]
### Description

1. Create new endpoints with the name is "/users/create" (method POST).
2. When you call "/users/create" by the postman, 1 record (fixed data) has been inserted into the User Table.

Ref: https://stackoverflow.com/questions/23560665/how-to-insert-data-into-table-using-django
`book = Publisher(name=p1, address=p2)`
`book.save()`

3. Same as above, create "/users/update" (method PUT) to update 1 record by id (fixed data).

Ref:
`user = Users.objects.filter(id="1")`
`user.name = "Han"`
`user.save()`

4. Same as above, create "/users/delete" (method DELETE).

**Comment by ngochan21098** [comment]
@ddhienpy Please review my PR 
- https://github.com/ngochan21098/learning-django-basic/pull/4

**Comment by ddhienpy** [comment]
@ngochan21098 
[Update Requirement]
1. Thêm API get by id (primary_key) cho tất cả các model. (VD: GET /users/:id) => Trả về thông tin của User đó.
2. Chuyển đổi toàn bộ API create/update/delete lấy từ Body của request.
- Với API update và delete thì id sẽ lấy từ url (VD: PUT /users/:id => API update), (DELETE /users/:id => API delete).
3. Chuyển đổi sang sử dụng @api_view(["POST"]) của rest_framework.

*Note: Cách lấy :id từ url
`path("listing/<int:id>/", views.listing, name = "listing")`

`@api_view(["POST"])
def create_user(req, id):`

**Comment by ngochan21098** [comment]
@ddhienpy Please review my PR 
- https://github.com/ngochan21098/learning-django-basic/pull/6

**Comment by ddhienpy** [comment]
@ngochan21098 
Thank you. I have approved it.
